Updates to azdo pipeline

diff --git a/.azuredevops/markdown2pdf.yml b/.azuredevops/markdown2pdf.yml
--- a/.azuredevops/markdown2pdf.yml
+++ b/.azuredevops/markdown2pdf.yml
@@ -1,10 +1,9 @@
-# pipeline version: 3.0.1
 trigger: none
 pr:
   autoCancel: true
   drafts: false
 
-name: 🧳 Convert Markdown
+name: 📝 Convert Markdown
 
 variables:
   FIRST_CHANGE_DESCRIPTION: Initial draft
@@ -19,38 +18,53 @@ variables:
   SUBTITLE: Design Document
   TITLE: DNS
   REPLACE_FILE:
-  VERSION_ACTION: v3.0.2beta1
+  WORKFLOW_VERSION: v3.0.2beta1
 
 pool:
   vmImage: ubuntu-22.04
-
-container: pandoc/extra:edge-ubuntu
 
 steps:
   - checkout: self
     displayName: Checkout
     fetchDepth: 0
 
+  - task: Cache@2
+    displayName: Cache TeX Live
+    inputs:
+      cacheHitVar: TEX_LIVE_CACHE_RESTORED
+      key:  |
+        "texlive" | "$(Agent.OS)" | $(Build.SourceVersion)
+      path: /opt/texlive
+      restoreKeys: |
+        "texlive" | "$(Agent.OS)"
+
   - task: Bash@3
     displayName: Install tools
     env:
       SCRIPT: install-tools
-      VERSION: ${{ variables.VERSION_ACTION }}
+      VERSION: ${{ variables.WORKFLOW_VERSION }}
     inputs:
       targetType: inline
       script: |
-        HTTP_CODE=$(curl --show-error --silent --remote-name \
-          --write-out "%{response_code}" \
-          --header 'Accept: application/vnd.github.raw' \
-          --location https://github.com/innofactororg/markdown2pdf/raw/${VERSION}/tools/${SCRIPT}.sh
+        files=(
+          "${SCRIPT}.sh"
+          texlive.profile
+          texlive_packages.txt
+          pip_requirements.txt
         )
-        if [[ ${HTTP_CODE} -lt 200 || ${HTTP_CODE} -gt 299 ]]; then
-          echo "##[error]Unable to get ${SCRIPT} script! Response code: ${HTTP_CODE}"
-          exit 1
-        fi
-        git config --global --add safe.directory '*'
-        chmod +x ${SCRIPT}.sh
-        ./${SCRIPT}.sh
+        for file in "${files[@]}"; do
+          HTTP_CODE=$(curl --show-error --silent --remote-name \
+            --write-out "%{response_code}" \
+            --header 'Accept: application/vnd.github.raw' \
+            --location "https://github.com/innofactororg/markdown2pdf/raw/${VERSION}/tools/${file}"
+          )
+          if [ "${HTTP_CODE}" -lt 200 ] || [ "${HTTP_CODE}" -gt 299 ]; then
+            echo "##[error]Unable to get ${file}! Response code: ${HTTP_CODE}"
+            exit 1
+          fi
+        done
+        chmod +x "${SCRIPT}.sh"
+        ./"${SCRIPT}.sh"
 
   - task: Bash@3
     displayName: Build PDF
@@ -61,31 +75,38 @@ steps:
       HISTORY: ${{ variables.HISTORY_FILE }}
       LIMIT: ${{ variables.GIT_LOG_LIMIT }}
       SCRIPT: convert
-      VERSION: ${{ variables.VERSION_ACTION }}
+      VERSION: ${{ variables.WORKFLOW_VERSION }}
     inputs:
       targetType: inline
       script: |
-        HTTP_CODE=$(curl --show-error --silent --remote-name \
-          --write-out "%{response_code}" \
-          --header 'Accept: application/vnd.github.raw' \
-          --location https://github.com/innofactororg/markdown2pdf/raw/${VERSION}/tools/${SCRIPT}.sh
+        files=(
+          "${SCRIPT}.sh"
+          designdoc.tex
+          designdoc-cover.png
+          designdoc-logo.png
         )
-        if [[ ${HTTP_CODE} -lt 200 || ${HTTP_CODE} -gt 299 ]]; then
-          echo "##[error]Unable to get ${SCRIPT} script! Response code: ${HTTP_CODE}"
-          exit 1
-        fi
+        for file in "${files[@]}"; do
+          HTTP_CODE=$(curl --show-error --silent --remote-name \
+            --write-out "%{response_code}" \
+            --header 'Accept: application/vnd.github.raw' \
+            --location "https://github.com/innofactororg/markdown2pdf/raw/${VERSION}/tools/${file}"
+          )
+          if [ "${HTTP_CODE}" -lt 200 ] || [ "${HTTP_CODE}" -gt 299 ]; then
+            echo "##[error]Unable to get ${file}! Response code: ${HTTP_CODE}"
+            exit 1
+          fi
+        done
         git config --global --add safe.directory '*'
-        chmod +x ${SCRIPT}.sh
-        ./${SCRIPT}.sh -a "${AUTHOR}" -d "${DESCRIPTION}" -f "${FOLDER}" \
-          -force "${SKIP_GIT_HISTORY}" -h "${HISTORY}" -l ${LIMIT} \
+        chmod +x "${SCRIPT}.sh"
+        ./"${SCRIPT}.sh" -a "${AUTHOR}" -d "${DESCRIPTION}" -f "${FOLDER}" \
+          -force "${SKIP_GIT_HISTORY}" -h "${HISTORY}" -l "${LIMIT}" \
           -o "${ORDER_FILE}" -out "${OUT_FILE}" -p "${PROJECT}" \
           -r "${REPLACE_FILE}" -s "${SUBTITLE}" -t "${TITLE}" \
           --template "designdoc"
 
   - task: PublishPipelineArtifact@1
     displayName: Publish PDF
-    condition: always()
     inputs:
-      targetPath: $(Pipeline.Workspace)/${{ variables.OUT_FILE }}
+      targetPath: $(Build.SourcesDirectory)/${{ variables.OUT_FILE }}
       artifact: ${{ variables.OUT_FILE }}
       publishLocation: pipeline
